# Generated by Django 5.1.3 on 2024-11-19 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket'), ('badminton', 'Badminton'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('fair', 'Fair')], max_length=50)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='equipment_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
