# Generated by Django 5.1.3 on 2024-11-19 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='phone_number',
            field=models.CharField(default=0, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Enter a valid phone number.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s]+$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'Price must be greater than zero.')]),
        ),
    ]
