# Generated by Django 5.1.3 on 2024-11-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kick', '0002_equipment_phone_number_alter_equipment_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='phone',
        ),
    ]
