# Generated by Django 5.1.3 on 2024-11-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kick', '0003_remove_equipment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='equipment',
            name='phone',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
