# Generated by Django 5.1.3 on 2024-11-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kick', '0004_remove_equipment_phone_number_equipment_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
