# Generated by Django 5.1.3 on 2024-11-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kick', '0006_equipment_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket'), ('badminton', 'Badminton'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball'), ('basketball', 'Basketball')], max_length=50),
        ),
    ]
